version: '3.8'

services:
  # n8n workflow automation
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n-local
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=0.0.0.0
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - NODE_ENV=development
      - N8N_BASIC_AUTH_ACTIVE=false  # Disable auth for local dev
      - N8N_COMMUNITY_PACKAGES_ALLOW_TOOL_USAGE=true
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - victoury-local

  # Victoury MCP HTTP Server
  victoury-mcp:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    container_name: victoury-mcp-local
    command: ["npm", "run", "http-server"]
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - HTTP_PORT=3000
      - NODE_ENV=development
      # No API credentials here - they come from n8n requests
    networks:
      - victoury-local
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 3

networks:
  victoury-local:
    driver: bridge

volumes:
  n8n_data:
    name: n8n_local_data