version: '3.8'

services:
  # Production MCP Server with enhanced security
  victoury-mcp:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: victoury-mcp-server
    command: ["node", "dist/http-server-secure.js"]
    restart: unless-stopped
    ports:
      - "${HTTP_PORT:-3000}:3000"
    env_file:
      - ./envs/production.env
    environment:
      - NODE_ENV=production
      - HTTP_PORT=3000
      - HTTP_API_KEY=${HTTP_API_KEY}
      - RATE_LIMIT_PER_MINUTE=${RATE_LIMIT_PER_MINUTE:-100}
    networks:
      - victoury-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Redis for session/cache management
  redis:
    image: redis:7-alpine
    container_name: victoury-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}
    volumes:
      - redis_data:/data
    networks:
      - victoury-network
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Optional: Nginx reverse proxy with SSL
  nginx:
    image: nginx:alpine
    container_name: victoury-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - nginx_logs:/var/log/nginx
    networks:
      - victoury-network
    depends_on:
      - victoury-mcp

networks:
  victoury-network:
    driver: bridge
    name: victoury-production-network

volumes:
  redis_data:
    name: victoury_redis_data
  nginx_logs:
    name: victoury_nginx_logs