# Environment Configuration Definitions
# This file defines the available environments and their characteristics

environments:
  development:
    description: "Local development environment"
    characteristics:
      - Hot reload enabled
      - Verbose logging
      - No resource limits
      - Port 3000
    defaults:
      NODE_ENV: development
      LOG_LEVEL: debug
      HOST_PORT: 3000
      
  staging:
    description: "Staging/testing environment"
    characteristics:
      - Production-like setup
      - Moderate logging
      - Resource limits applied
      - Port 3001
    defaults:
      NODE_ENV: production
      LOG_LEVEL: info
      HOST_PORT: 3001
      
  production:
    description: "Production environment"
    characteristics:
      - Optimized for performance
      - Minimal logging
      - Strict resource limits
      - Port 3002
    defaults:
      NODE_ENV: production
      LOG_LEVEL: warn
      HOST_PORT: 3002

# Port allocation guide
# This helps avoid port conflicts when running multiple environments
port_allocation:
  development: 3000
  staging: 3001
  production: 3002
  
# Deployment notes
deployment_notes:
  - "Always test in staging before deploying to production"
  - "Use --rebuild flag when updating dependencies"
  - "Monitor logs after deployment for any issues"
  - "Keep environment files secure and never commit them"

# Health check endpoints
health_checks:
  path: "/health"
  expected_status: 200
  timeout: 10s
  
# Backup recommendations
backup_strategy:
  configs: "Daily backup of environment files"
  logs: "Rotate logs weekly, archive monthly"
  frequency: "Automated daily at 2 AM"