# Multi-Environment Configuration
# Pattern: {client}-{environment}

environments:
  # Client A environments
  client-a-dev:
    port: 3010
    build_args:
      NODE_ENV: development
    description: "Client A - Development"
    
  client-a-staging:
    port: 3011
    build_args:
      NODE_ENV: staging
    description: "Client A - Staging"
    
  client-a-prod:
    port: 3012
    build_args:
      NODE_ENV: production
    description: "Client A - Production"
    
  # Client B environments  
  client-b-dev:
    port: 3020
    build_args:
      NODE_ENV: development
    description: "Client B - Development"
    
  client-b-prod:
    port: 3021
    build_args:
      NODE_ENV: production
    description: "Client B - Production"
    
  # Client C - maybe only needs prod
  client-c-prod:
    port: 3030
    build_args:
      NODE_ENV: production
    description: "Client C - Production"
    
  # Internal testing
  internal-dev:
    port: 3000
    build_args:
      NODE_ENV: development
    description: "Internal Development"
    
  internal-staging:
    port: 3001
    build_args:
      NODE_ENV: staging
    description: "Internal Staging"